-- BizTrack PostgreSQL Schema Initialization
-- Target Database: Supabase / PostgreSQL
-- Description: Standard initialization migration script to setup sales and expenses schemas, receipt columns, and indices.

-- 1. Sales Table Schema
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    receipt TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) on Sales
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;

-- Create Policies for Sales
CREATE POLICY "Allow owners full control on sales" ON public.sales
    FOR ALL
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Performance Index for Sales
CREATE INDEX IF NOT EXISTS idx_sales_user_date ON public.sales(user_id, date);


-- 2. Expenses Table Schema
CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    date DATE NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount >= 0),
    vendor TEXT NOT NULL DEFAULT 'Imported Vendor',
    receipt TEXT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) on Expenses
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;

-- Create Policies for Expenses
CREATE POLICY "Allow owners full control on expenses" ON public.expenses
    FOR ALL
    TO authenticated
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Performance Index for Expenses
CREATE INDEX IF NOT EXISTS idx_expenses_user_date ON public.expenses(user_id, date);
